juttle/outrigger

- bin/outriggerd
- lib/app-router.js
Production mode installations where webpack doesn't exist were failing
to run because they still required webpack at the top level.
Fix this by deferring the requires inside the conditional check for
dev mode.
> fix production mode problems by deferring webpack requires

- log4js.json
- package.json
Fix a few issues that occurred when running from the npm installation as opposed to from the source tree.
First, make sure to include the dist directory in the npm published package. This is a followup to the changes in #1 which fixed the require problem, but still failed to run because of the missing dist dependency.
Also fix the logic used to find the dist directory to be based on the file location and not the cwd from where outriggerd is run.
Second, address #4 by removing the default file appender from log4js since it depends on a `./log` directory existing in the cwd which is not necessarily the case.
> fix npm installation issues

- README.md
The juttle config docs got moved down to the cli docs, so point to the
new location. This required using a slightly uglier way to point to
the docs.
Also change the relative link to the architecure section to use a
format that npm can rewrite without problems.
@demmer @mnibecker
> Fix some links in README.md.

- README.md
- bin/outrigger-client
Tidy up the spacing in outrigger-client --help. Update README.md to
refer to a single outrigger daemon and not separate juttled/app
servers.
@mnibecker @davidvgalbraith
> Clean up outrigger-client usage.

- package.json
The correct string to use is 0.1.x to match all subversions of 0.1.
@mnibecker @demmer
> Fix peer dependency.

- lib/bundler.js
`JuttleError` wraps all Juttle errors and it is a parent class of `SyntaxError`/`CompileError`/`RuntimeError`, so there is no need to test for them separately.
> JuttleBundler: Use JuttleError in instanceof check

- lib/service-juttled.js
Could only connect to outriggerd using `localhost:2000`, a relic of our pre-release days. I figure for now outrigger should accept requests from all origins.
@mstemm
> Allow all origins for cors

- src/client-lib/middleware/job-socket.js
- Also move date parsing code in job-socket middleware into the client-socket-manager.
The juttle-viz views expect these values to be JavaScript Dates and not JSON serialized string representations of Dates which is what we get over the websocket.
@mnibecker, as we discussed, this code will be removed shortly anyways, since its being extracted out into [juttle-client-library](https://github.com/juttle/juttle-client-library). This "patch" should be applied there.
> client-socket-manager: parse _jut_time_bounds from and to to dates

- src/client-lib/containers/input-group.js
Simple enough fix, lets hope this passes tests.
> Add newly required semicolon to es6 class property

- .travis.yml
- lib/juttle-subprocess.js
- package.json
- Bump the juttle peerDependency to 0.2.x.
- Update juttle-subprocess to the modified program API in juttle 0.2.x.
Note that this does not do the full rename of "sink" to "view" (#27).
> update to juttle v0.2.0

- src/client-lib/utils/api.js
So that the API calls his the same host/port that the app was fetched from.
@mnibecker 
cc @dmehra this is to make outrigger work in docker correctly.
> api.js: remove hard coded localhost and port

- lib/app-router.js
Now the router always searches for the `dist` dir in a location
relative to the file lib/app-router.js instead of partially by
the cwd and partially by the __dirname of the file.
> app-router: don't depend on the cwd to look for the dist dir

- demos/core-juttle/README.md
- demos/core-juttle/chart_gallery.juttle
- demos/core-juttle/fizzbuzz.juttle
- demos/core-juttle/hello_world.juttle
- demos/core-juttle/kitchen_duty.juttle
- demos/core-juttle/sine_wave.juttle
- demos/core-juttle/stock_prices.juttle
@demmer @mccanne these are the demos that used to be [private here](https://github.com/juttle/outrigger-pre-open/tree/demo-2015-12-09) including the stock prices, kitchen duty, and math. They work on outrigger 0.2.0. 
We can add instructions for using in the docker container tomorrow.
> Adding demo of basic juttle programs incl http adapter

- demos/core-juttle/README.md
The correct command to run is "outrigger-client browser", not
"run". "run" runs the program without any interaction with the
browser.
Change the outriggerd command to daemonize and write to a log file by
default. This assumes the changes in #47 have been merged.
@dmehra @demmer @mccanne
> Fix minor problems in demo README.

- demos/core-juttle/sine_wave.juttle
FYI @dmehra here's the sine_wave example with overlaid event threshold alerting based on a windowed moving average.
> demos: update sine_wave example to have an alert threshold

- README.md
So that the badge isn't red when other branches are failing.
@mnibecker @mstemm
> travis badge: show build status for master branch

- src/apps/run/main.js
We were using a describe call when we should have calling path. Use path
instead. Change response to res and submit bundle to initBundle.
@go-oleg
> Fix issues with browser mode for client

- lib/job-handlers.js
- lib/job-manager.js
- lib/juttle-subprocess.js
- lib/service-juttled.js
Plumb the --config argument down to the JuttleJob as an option
config_file. It is passed to the spawned subprocess as the only
process argument.
The subprocess in turn calls read_config with argv[2]. If undefined,
it falls back to the default set of search paths.
This fixes #62.
@demmer
> Pass config path to juttle subprocess.

- .travis.yml
juttle is now a true dependency instead of a peerDependency so it will get installed by `npm install`
@rlgomes
> travis: don't explicitly install juttle

- lib/job-handlers.js
- lib/job-manager.js
- lib/service-juttled.js
- lib/websocket-endpoint.js
- test/juttled/juttled.spec.js
Allow late-joining websockets to get a program's output even after a
job ends by adding a configurable delay before actually removing a job
from the job manager's set of jobs. This can be changed by
juttle-config's juttled.lingering_job_timeout option, and defaults to
10 seconds.
During the lingering timeout, the job is marked as stopped. When
adding an endpoint to a job, do a second check to see if the job is
stopped. If it is, replay all messages, send the job_stop message, and
close the connection.
This revealed a possible race condition where a endpoint.close() could
be called before all messages have actually been sent. To address
this, add a flag endpoint:_closing which is set to true in
endpoint.close() if there are queued messages. In drain() once the
queue is empty it calls …
> Allow late-joining websockets to get program output.

- bin/juttle
- package.json
Include a simple `bin/juttle` script that resolves the local juttle
installation and then requires it. This way an installation of outrigger
will make it easy to run juttle CLI commands as well.
> add a wrapper script to expose bin/juttle in an outrigger installation

- lib/job-manager.js
- lib/websocket-endpoint.js
There are cases where JuttleJob::close() can be legitimately called
multiple times:
- When a job is being stopped internally (e.g. due to the program
exiting).
- When a job is being stopped externally (e.g. due to an explicit
command to stop the job, or due to all websocket connections
exiting for a job).
There isn't any harm from this happening, but I did notice these
errors in the logs that resulted from sending the spawned subprocess a
redundant 'end' message:
[2016-01-14 16:16:20.730] [DEBUG] demo-job-manager - Removing job 3a79b595-7e93-47bc-9764-5cd0ec216143 from jobs hash
[2016-01-14 16:16:20.730] [DEBUG] demo-job-manager - (job=3a79b595-7e93-47bc-9764-5cd0ec216143) Stopping job
[2016-01-14 16:16:20.731] [ERROR] demo-job-manager - Received error Error: channel closed from …
> Don't send redundant messages to subprocess.

- examples/core-juttle/stock_prices.juttle
Tweak the juttle used to render the chart so that we treat the
price series differently from the volume series.
For the prices, simply remove any values that are null so the chart
appears as a continuous line instead of dropping down to zero each
time.
For the volume however, keep the old behavior that converted a null
to a zero value.
@dmehra
> examples: update stock price example

- lib/juttle-subprocess.js
- test/juttled/juttled.spec.js
Use JSDP to serialize messages sent from the juttle-subprocess to job-manager (which then get passed through to the websocket).
@mstemm
This may be going overboard with JSDP a bit by serializing everything juttle-subprocess sends and not just values from juttle itself, but job-manager just passes through everything it receives from the juttle-subprocess to the websocket. May want to look into creating a stricter separation between juttle-subprocess <-> job-manager and job-manager <-> websocket communication in the future.
> use jsdp to serialize messages from juttle-subprocess to job-manager

- examples/README.md
- examples/gmail/README.md
- examples/gmail/index.juttle
- examples/gmail/messages_by_sender.juttle
- examples/gmail/messages_by_time.juttle
- examples/gmail/write_results.juttle
- examples/index.juttle
- examples/twitter-race/README.md
- package.json
Add a note to the top level README/index.juttle referring to the gmail directory.
In the gmail directory, add a index.juttle, a README.md, and 3 programs:
- messages_by_sender: read the last 12 hours of messages and categorize by sender. You can specify any gmail search expression in an input.
- messages_by_time: read the last 12 hours of messages sent to "me" and categorize by time received.
- write_results: write some artificial data to gmail (i.e. send in an email).
Update outrigger to v0.3.0 of the gmail adapter so it has write support and support for filter expressions.
I also snuck in an unrelated change to fix a typo in the twitter README.
In order for these examples to work with the outrigger docker image,
I'll have to npm publish outrigger 0.4.0 and publish a new docker
image to …
> Add gmail adapter examples.

- src/apps/run/components/juttle-viewer.js
- src/apps/run/index.html
- src/apps/run/main.js
- src/apps/sass/main.scss
Add a basic show/hide juttle toggle link
- starts off hidden
- expands to max-height of 200px and then scrolls
Resolves #59 
let me know if you want any styling changes
@mnibecker @davidvgalbraith 
cc @dmehra
> add 'show juttle' toggle to view juttle source

- docker/images/elastic_news_data/Dockerfile
- docker/images/elastic_news_data/README.md
- examples/elastic-newstracker/README.md
- examples/elastic-newstracker/dc-elastic-loadfromscratch.yml
- examples/elastic-newstracker/dc-elastic.yml
- examples/elastic-newstracker/num_elastic_points.juttle
- examples/elastic-newstracker/top_linked_pages.juttle
- examples/elastic-newstracker/top_linked_pages_read_rollup.juttle
- examples/elastic-newstracker/top_linked_pages_write_rollup.juttle
The load time for the elastic demo was pretty long, so make some
changes to reduce the size of the data and also use a preloaded
version that can be downloaded directly from docker hub.
See the specific commits, but the general changes are:
- Shrink the size of the dataset to a 10% sample.
- Preload the data in a docker container containing /usr/share/elasticsearch/data
- Use that container to get an elasticsearch with preloaded preindexed data.
@VladVega you might want to try this technique for examples using the db-based adapters.
@dmehra @demmer
> Shrink and preload the news data from a container.

- gulpfile.js
- package.json
- test/lib/juttle-subprocess.spec.js
fixes #98
we were missing tests here that didn't depend on tracking the coverage
across spawn process which would be much harder to do.
> missing juttle-process tests

- src/apps/sass/juttle-client-library-overrides.scss
Override the [react-select](https://github.com/JedWatson/react-select) styling that comes from juttle-client-library
@mnibecker
> style select input for outrigger

- lib/juttle-subprocess.js
Make sure that all require()s have been called before calling
read_config(). We ran into a problem where read_config, which
internally calls logger.debug() for one of the paths, may call the
juttle-subprocess.js's getLogger function, which depends on modules in
juttle-subprocess.js.
@demmer @go-oleg
> Move read_config call after all require()s.

- examples/core-juttle/README.md
- examples/core-juttle/index.juttle
- examples/core-juttle/npm_download_counts.juttle
Now that we're using juttle 0.3.0, the http adapter supports -rootPath
to peek into json results. Use that for a new example program that
shows npm download counts.
This fixes #55.
> Add example program for npm download counts.

- examples/README.md
- examples/cadvisor-influx/README.md
- examples/cadvisor-influx/cadvisor-dashboard.juttle
- examples/cadvisor-influx/dc-cadvisor-influx.yml
- examples/cadvisor-influx/test.juttle
- examples/elastic-newstracker/dc-elastic.yml
- examples/index.juttle
- examples/juttle-config.json
- examples/twitter-race/README.md
connects to #24 
Our ability to run this demo is blocked on 2 things:
- [InfluxDB v0.9 support · Issue #743 · google_cadvisor](https://github.com/google/cadvisor/issues/743) - should be unblocked, it's merged, although not yet in the official release (use canary image)
- proper support for periodic reads to the backend in "live" mode, which was hacked up with '-lag' option in the pre-open version of this demo. The real influx adapter doesn't support '-lag' so the juttle here cannot run.
Don't merge these demo docs until the above are resolved, or else switch the demo to use a different backend (say Redis instead of Influx) or use something else (REST API?) instead of cadvisor to get the docker container stats.
@demmer @mstemm as we discussed... I will leave what's done here, and file an …
> Docker monitoring demo with cadvisor and influx

- package.json
0.2.1 has fixes that ensure barcharts work properly so we want to use
at least 0.2.1, even though ^0.2.0 will pick up the latest version.
@go-oleg
> Update to 0.2.1.

- examples/cadvisor-influx/dc-cadvisor-influx.yml
@demmer the 2-second setting which wasn't working before, is working now. I have no explanation other than the vagaries of running a canary build, perhaps.
> 2s buffer now works

- package.json
- test/app/lib/outrigger-tester.js
- test/juttled/juttled.spec.js
this will fix an issue that sometimes creeps up running tests locally
since we use the default 8080 port and as a developer you may have an
outriggerd instance already running.
> fixed tests to use find-free-port to avoid port collisions

- lib/jsdp-value-converter.js
The special moment values `:beginning:` and `:end:` are represented
internally as -Infinity and Infinity. While moment can (sort-of)
handle these, Date cannot, so outrigger blows up if one of these
values is used in the time range for read or in the points.
To work around this problem, convert infinite moments to the
smallest / largest legal Javascript date before encoding over
JSDP.
> jsdp-value-converter: add hack to handle infinite dates

- lib/ws-juttle-job.js
- test/juttled/juttled.spec.js
This is a fix for #131, taking parts of the fix from juttle-engine for
juttle/juttle-engine#9. I didn't bother with a fully configurable timeout.
I did copy over a unit test to ensure that there is a delay between
the job_end message and the websocket being closed.
Note that this PR is to merge to the 0.5.0 branch, which was based of off 0.5.0-rc.1.
> Don't close websocket connections immediately.
